

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DB_IRMOficial : DbContext
{
    public DB_IRMOficial()
        : base("name=DB_IRMOficial")
    {
        this.Configuration.LazyLoadingEnabled = false;
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<TB_IDIOMA> TB_IDIOMA { get; set; }

    public virtual DbSet<TB_POST> TB_POST { get; set; }

    public virtual DbSet<TB_TIPO_POST> TB_TIPO_POST { get; set; }

    public virtual DbSet<TB_TIPO_USUARIO> TB_TIPO_USUARIO { get; set; }

    public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }

    public virtual DbSet<TB_ACOES_POST> TB_ACOES_POST { get; set; }

    public virtual DbSet<TB_CONTEUDO> TB_CONTEUDO { get; set; }

    public virtual DbSet<TB_USUARIO_LOGIN> TB_USUARIO_LOGIN { get; set; }

    public virtual DbSet<TB_ACOES_CONTEUDO> TB_ACOES_CONTEUDO { get; set; }

    public virtual DbSet<TB_DOCUMENTO> TB_DOCUMENTO { get; set; }

}

}

