
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_ACOES_POST
{

    public int ID_ACOES_POST { get; set; }

    public bool FL_CURTIR { get; set; }

    public bool FL_NAO_CURTIR { get; set; }

    public int ID_POST { get; set; }

    public Nullable<int> ID_USUARIO { get; set; }

    public bool FL_PLAY { get; set; }

    public Nullable<System.DateTime> DT_ACAO_CURTIR { get; set; }

    public Nullable<System.DateTime> DT_ACAO_PLAY { get; set; }

    public bool FL_COMPARTILHAR { get; set; }

    public Nullable<System.DateTime> DT_ACAO_COMPARTILHAR { get; set; }



    public virtual TB_POST TB_POST { get; set; }

    public virtual TB_USUARIO TB_USUARIO { get; set; }

}

}
