
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_ACOES_CONTEUDO
{

    public int ID_ACOES_CONTEUDO { get; set; }

    public bool FL_CURTIR { get; set; }

    public System.DateTime DT_ACAO_CURTIR { get; set; }

    public int ID_CONTEUDO { get; set; }

    public int ID_USUARIO { get; set; }



    public virtual TB_CONTEUDO TB_CONTEUDO { get; set; }

    public virtual TB_USUARIO TB_USUARIO { get; set; }

}

}
