
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_CONTEUDO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TB_CONTEUDO()
    {

        this.TB_ACOES_CONTEUDO = new HashSet<TB_ACOES_CONTEUDO>();

    }


    public int ID_CONTEUDO { get; set; }

    public byte[] IM_IMAGEM { get; set; }

    public string DS_LINK { get; set; }

    public string DS_CONTEUDO { get; set; }

    public int NR_ORDEM { get; set; }

    public Nullable<bool> FL_VIDEO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_ACOES_CONTEUDO> TB_ACOES_CONTEUDO { get; set; }

}

}
