
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_DOCUMENTO
{

    public int ID_DOCUMENTO { get; set; }

    public string DS_NOME { get; set; }

    public string DS_DESCRICAO { get; set; }

    public System.DateTime DT_CADASTRO { get; set; }

    public Nullable<bool> FL_FIXO { get; set; }

    public int NR_ORDEM { get; set; }

    public string DS_ARQUIVO { get; set; }

}

}
