
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_POST
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TB_POST()
    {

        this.TB_ACOES_POST = new HashSet<TB_ACOES_POST>();

    }


    public int ID_POST { get; set; }

    public string DS_POST { get; set; }

    public System.DateTime DT_CADASTRO { get; set; }

    public int ID_TIPO_POST { get; set; }

    public int ID_IDIOMA { get; set; }

    public string DS_TITULO { get; set; }

    public byte[] IM_IMAGEM { get; set; }

    public string DS_AUDIO { get; set; }

    public int NR_ORDEM { get; set; }

    public Nullable<bool> FL_FIXO { get; set; }

    public string DS_IMAGEM { get; set; }



    public virtual TB_IDIOMA TB_IDIOMA { get; set; }

    public virtual TB_TIPO_POST TB_TIPO_POST { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_ACOES_POST> TB_ACOES_POST { get; set; }

}

}
