
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_POPUP
{

    public int ID_POPUP { get; set; }

    public string DS_TITULO { get; set; }

    public string DS_POPUP { get; set; }

    public string DS_IMAGEM { get; set; }

    public Nullable<bool> FL_ATIVO { get; set; }

    public Nullable<System.DateTime> DT_POPUP { get; set; }

}

}
