
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_USUARIO_LOGIN
{

    public int ID_USUARIO_LOGIN { get; set; }

    public System.DateTime DT_LOGIN { get; set; }

    public Nullable<int> ID_USUARIO { get; set; }



    public virtual TB_USUARIO TB_USUARIO { get; set; }

}

}
