
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class TB_USUARIO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TB_USUARIO()
    {

        this.TB_ACOES_POST = new HashSet<TB_ACOES_POST>();

        this.TB_USUARIO_LOGIN = new HashSet<TB_USUARIO_LOGIN>();

        this.TB_ACOES_CONTEUDO = new HashSet<TB_ACOES_CONTEUDO>();

    }


    public int ID_USUARIO { get; set; }

    public string DS_NOME { get; set; }

    public string DS_EMAIL { get; set; }

    public string DS_SENHA { get; set; }

    public string DS_CIDADE { get; set; }

    public string DS_ESTADO { get; set; }

    public string DS_PAIS { get; set; }

    public System.DateTime DT_CADASTRO { get; set; }

    public int ID_TIPO_USUARIO { get; set; }

    public string DS_PAIS_SIGLA { get; set; }



    public virtual TB_TIPO_USUARIO TB_TIPO_USUARIO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_ACOES_POST> TB_ACOES_POST { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_USUARIO_LOGIN> TB_USUARIO_LOGIN { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_ACOES_CONTEUDO> TB_ACOES_CONTEUDO { get; set; }

}

}
