
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRM_Oficial
{

using System;
    using System.Collections.Generic;
    
public partial class VW_RANK_SEMANAL
{

    public Nullable<long> POSICAO_RANK { get; set; }

    public int ID_USUARIO { get; set; }

    public string DS_NOME { get; set; }

    public Nullable<int> COMPARTILHAMENTO { get; set; }

    public Nullable<int> CURTIR { get; set; }

    public Nullable<int> PLAY { get; set; }

    public Nullable<int> TOTAL { get; set; }

}

}
